go_library(
    name = "go_default_library",
    srcs = ["keymanager.go"],
    visibility = ["//visibility:public"],
    deps = ["@com_github_Sirupsen_logrus//:go_default_library"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_library")
